// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Km56.MyStore.Infrastructure.Sql
{
    [Index("Id", Name = "IX_Item_Identity", IsUnique = true)]
    public partial class Item
    {
        public int Id { get; set; }
        [Key]
        [StringLength(50)]
        [Unicode(false)]
        public string ItemNo { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string Description { get; set; }
    }
}